### PR TITLE
Initialize all structure members and fix warnings

### PR DESCRIPTION
**Pull request by SevenBits**
This pull request:

- Fixes compiler warnings caused by the `stx` structure not being initialized properly
- Enables strong warning detection and enables treating warnings as errors

More patches may be coming shortly.

### CODE REVIEW

**Comment by toddgaunt** [comment]
Hey, its cool that you've taken interest in this project! Looking through your changes I wanted to comment on the struct initialization thing in C. When initializing a struct in C, its enough to initialize all members of a struct like so:

struct foo f = {0};

This will initialize all values of the struct to 0 or NULL (except for any structure padding). Also, the flags you added to the Makefile were already in config.mk. I don't blame you for the confusion though, as my project still needs to get it's layout and structure documented more, like a developers.txt file or something.

**Comment by toddgaunt** [comment]
I'm going to close this request for now since I believe it was just a misunderstanding of C struct initialization syntax. I tried looking through most of the files and it's all I could see what was changed (I appreciate the intentions though).

**Comment by SevenBits** [comment]
Hi @toddgaunt, I’m well aware of the C syntax rules; you are correct in your statement. Please see page 125 of the [C99 standard][1], which says this:

> If there are fewer initializers in a brace-enclosed list than there are elements or members of an aggregate, or fewer characters in a string literal used to initialize an array of known size than there are elements in the array, the remainder of the aggregate shall be initialized implicitly the same as objects that have static storage duration.

So you are correct. However, I don’t like seeing warnings when I compile code, even if it’s a result of an overly paranoid C compiler complaining about otherwise complaint code. There does exist a GCC option `-Wno-missing-field-initializers` to disable this warning, but I find it’s cleaner to initialize a struct fully rather than relying on disabling compiler warnings.

Feel free to use this if you want, instead of my patch. Not sure if it works on clang, but it should on GCC.

[1]: http://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf

**Comment by toddgaunt** [comment]
Oh that's weird, sorry about the unneeded lesson on C syntax then haha. I just don't get those warning by default on Slackware. Also I totally get where you're coming from when you say you don't like the compiler warnings, and it would drive me nuts, however I prefer the "= {0}" because I don't receive those warnings. What compiler version are you using?

**Comment by toddgaunt** [comment]
btw @SevenBits, I was wondering are you using this at all or do you plan to? It would be cool to see someone other than me using this string library.

**Comment by SevenBits** [comment]
> What compiler version are you using?

Stated in the other thread.

> I was wondering are you using this at all or do you plan to? It would be cool to see someone other than me using this string library.

I’m currently evaluating various open-source string libraries for use with a project that’s still in the planning stages. I came across your library and thought about evaluating it. How would you compare your project to e.g. [@antirez/sds][1]?

Incidentally, does this library work with ulibc or musl, or does it require GNU libc?

[1]: https://github.com/antirez/sds

**Comment by toddgaunt** [comment]
I haven't directly tested musl recently, but I only follow ANSI C99 (with some C11 sugar optionally) and I actively avoid GNU dependencies, so yes ulibc or musl should work perfectly well.

My project isn't as simple as SDS, nor as battle tested (Its just been me working and tweaking with it, however I try to thoroughly test it with my tests in 'test/'), but I made it because I wasn't too fond of the was SDS or glib GString auto-allocated the string's buffer.

What I mean by this is that SDS and GString will automatically realloc the memory the characters lie in, and usually allocate more than is sometimes necessary (GString allocated in powers of two).

My goal was to write a library compatible with both stack allocated buffers and dynamically allocated buffers and make it easy to be sure that none of the functions other than the memory allocation ones would because of a failed realloc() call. Also, every function that "cannot fail" can be composed together, since a pointer to a 'stx' struct is returned by  most functions, and will never be NULL.

Also, the simplest comparison I can make for this library is that stxs are a lot like Rust's strings, where mutable, dynamic strings have a separate structure from immutable reference structs but they can be converted between one-another easily.

All of the current functions for the library are finished as well, the only things I am currently working on are finishing the rest of the regression tests and manpage documentation.

Overall, I'd say I'd recommend this library if you care about memory allocations and string reference safety.

**Pull request closed without merging**
